# Generated by Django 6.0.4 on 2026-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lezzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Lezzet Adı')),
                ('kategori', models.CharField(choices=[('Sıcak İçecek', 'Sıcak İçecek'), ('Soğuk İçecek', 'Soğuk İçecek'), ('Tatlı & Pasta', 'Tatlı & Pasta'), ('Fırından', 'Fırından')], max_length=50, verbose_name='Kategori')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('fiyat', models.CharField(max_length=20, verbose_name='Fiyat (Örn: 150 TL)')),
                ('renk', models.CharField(default='from-pink-500 to-rose-500', max_length=100, verbose_name='Renk Geçişi CSS')),
                ('ikon', models.CharField(default='fa-mug-hot', max_length=50, verbose_name='FontAwesome İkon')),
                ('resim', models.URLField(max_length=500, verbose_name='Resim URL')),
                ('aktif', models.BooleanField(default=True, verbose_name='Sitede Gösterilsin mi?')),
                ('sira', models.IntegerField(default=0, verbose_name='Görüntülenme Sırası')),
            ],
            options={
                'verbose_name': 'Lezzet',
                'verbose_name_plural': 'Lezzetler',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('mesaj', models.TextField(verbose_name='Mesaj veya Rezervasyon Detayı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('okundu', models.BooleanField(default=False, verbose_name='İncelendi / Okundu')),
            ],
            options={
                'verbose_name': 'Rezervasyon & Mesaj',
                'verbose_name_plural': 'Rezervasyonlar & Mesajlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
