# Generated by Django 6.0.4 on 2026-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezzet',
            name='rozet',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Özel Rozet'),
        ),
    ]
