# Generated by Django 6.0.4 on 2026-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lezzet_rozet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezzet',
            name='diyet',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Diyet & Besin Etiketleri'),
        ),
    ]
