# Generated by Django 6.0.4 on 2026-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lezzet_diyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezzet',
            name='sure',
            field=models.CharField(blank=True, default='⏱️ 4-6 Dk', max_length=50, verbose_name='Hazırlanma Süresi'),
        ),
    ]
